require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.6.3
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'app/views/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'storage/**/*'
    - 'tmp/**/*'

Performance:
  Exclude:
    - '**/test/**/*'
